// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-nMwjLmy2jocs9dhHIzk4AD771tuBtGU',
    appId: '1:137425184726:android:edda76320e436be49f6677',
    messagingSenderId: '137425184726',
    projectId: 'diaryapp-51d01',
    databaseURL: 'https://diaryapp-51d01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-51d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJpVmqNrv5jkK9gs4tmiad4Ivei_oENhI',
    appId: '1:137425184726:ios:df91cbdbd14b2f0b9f6677',
    messagingSenderId: '137425184726',
    projectId: 'diaryapp-51d01',
    databaseURL: 'https://diaryapp-51d01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-51d01.appspot.com',
    iosBundleId: 'com.diary.app.thesis.mobileApp',
  );
}
